import Head from "next/head";
import MainContent from "../components/MainContent";
import Hero from "@/components/hero/Hero";
import { GetServerSideProps } from "next";
import Create from "@/components/create/Create";
import { useAuthState } from "react-firebase-hooks/auth";
import { auth } from "@/firebase.config";
import { User } from "firebase/auth";
import { Dispatch, SetStateAction } from "react";
import Loading from "@/components/Loading";
import About from "@/components/About";

export default function Home(props: {
  isLoading: boolean;
  currentUser: User;
  setCurrentUser: Dispatch<SetStateAction<User | undefined>>;
}) {
  if (props.isLoading) {
    return (
      <>
        <Head>
          <title>Turbobiz</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="author" content="Vidit Khandelwal" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <Loading />
      </>
    );
  }

  return (
    <>
      <Head>
        <title>Turbobiz</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="author" content="Vidit Khandelwal" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MainContent>
        <About/>
      </MainContent>
    </>
  );
}
