import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import MainContainer from "../components/MainContainer";
import MainContent from "../components/MainContent";
import Header from "@/components/header/Header";
import Hero from "@/components/hero/Hero";
import Title from "@/components/Title";
import Subtitle from "@/components/Subtitle";
import Categories from "@/components/create/Categories";
import createStyles from "@/styles/create.module.css";
import {
  BsArrowCounterclockwise,
  BsArrowUpRight,
  BsArrowRight,
} from "react-icons/bs";
import { motion } from "framer-motion";

import { Darker_Grotesque } from "@next/font/google";
import Link from "next/link";
import MainLink from "@/components/MainLink";
import Categories2 from "@/components/create/Categories2";
import Results from "@/components/create/Results";
import BasicCategories from "@/components/create/BasicCategories";

const dg = Darker_Grotesque({
  variable: "--darker-grotesque-font",
  subsets: ["latin"],
  weight: "600",
});

export default function Home() {
  const primaryLinkVariants = {
    hover: {
      backgroundColor: "#f87171",
      transition: { duration: 0.25, ease: "easeInOut" },
    },
  };

  const linkArrowVariants = {
    hover: {
      translateX: [0, 25],
      transition: {
        duration: 0.25,
        ease: "easeInOut",
      },
    },
  };

  return (
    <>
      <Head>
        <title>Turbobiz</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="author" content="Vidit Khandelwal" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MainContainer>
        <MainContent>
          <header id="header" className={createStyles.header}>
            <div className="flex flex-row space-x-1 items-center">
              <Title>turbobiz</Title>
            </div>
            <Subtitle>powered by OpenAI GPT-3</Subtitle>
          </header>
          <div className={"w-full h-full flex flex-col lg:flex-row"}>
            <div className="w-full lg:w-1/2 h-full flex flex-col justify-center pl-10 space-y-8">
              <div className="flex flex-col space-y-1">
                <Title>choose a category</Title>
                {/* <Categories2 /> */}
                <BasicCategories/>
              </div>
              {/* <div className="flex flex-col space-y-1">
                <Title size="sm">choose a sub-category</Title>
                <Categories2 />
              </div> */}
              <motion.div
                className="rounded-md bg-amber-400 w-72"
                variants={primaryLinkVariants}
                whileHover="hover"
              >
                <Link
                  href="/"
                  className={
                    "flex flex-row space-x-2 pl-4 pr-4 pt-2 pb-2 text-xl justify-between items-center " +
                    dg.className
                  }
                >
                  <motion.p>Generate</motion.p>
                  <motion.div className="pr-[25px]" variants={linkArrowVariants}>
                    <BsArrowRight className="text-xl" />
                  </motion.div>
                </Link>
              </motion.div>
            </div>
            <Results />
          </div>
        </MainContent>
      </MainContainer>
    </>
  );
}
