import e from "express";
import Subtitle from "./Subtitle";
import Title from "./Title";
import SecondaryLink from "./SecondaryLink";
import PrimaryLink from "./PrimaryLink";
import Code from "./Code";
import { AuthContext } from "@/AuthContext";
import { useContext } from "react";

const About = () => {
  const user = useContext(AuthContext);

  return (
    <div className="flex flex-col space-y-8">
      <Title>
        Turbobiz is a full-stack Next.js web application made by Vidit
        Khandelwal. It utilizes the power of cutting-edge generative artificial
        intelligence to accelerate your entrepreneurial spririt.
      </Title>
      <div className="flex flex-col space-y-4"></div>
      <Title>terms of use</Title>
      <div className="flex flex-col space-y-4 text-justify">
        <p className="">
          By using this product, you, the end user (also referred to as
          &quot;user&quot;, &quot;customer&quot;, &quot;client&quot;) agree to the terms of use listed below.
        </p>
        <p>
          Turbobiz (also referred to as the &quot;project&quot;, &quot;product&quot;,
          &quot;service&quot;) is made as a hobby project made by Vidit
          Khandelwal (also referred to as &quot;Vidit&quot;, &quot;we&quot;, &quot;us&quot;,
          &quot;he&quot;, &quot;him&quot;, &quot;his&quot;), free for public
          use. It is not meant for production or heavy usage, and does not claim
          to be suitable for such applications. The product has no hard limit on
          usage, but will employ reasonable fair use policy. We reserve the
          right to restrict, pause, or permanently halt access to the product to
          any person(s) who are found to be abusing the product, including, but
          not limited to, targeted DDoS attacks, unauthorized access to the
          product, internal APIs, or databases, circumventing security policy.
        </p>
        <p>
          The results provided by Turbobiz are parsed by custom code, and are
          based on the results given by OpenAI&apos;s Generative Pretrained
          Transformer (GPT) 4 Large Language Model (LLM), that is
          <Code>gpt-4</Code>, OR the GPT 3.5 Turbo <Code>gpt-3.5-turbo</Code>
          model, represented by their formal and API usage names respectively.
          The specific LLM model used in the product may be changed without
          prior notice to any end user, temporarily or permanently as per the
          needs of the product. The usage of either of these LLMs may is subject
          to OpenAI&apos;s API usage policy and as a result we are required to
          comply with it. Any resemblance to real life existing businesses,
          products, ideas, or entities is purely coincidental, unintentional,
          and an occassional occurence due to the very nature of generative
          artificial intelligence. Neither Turbobiz nor Vidit take any
          responsibility for such results. Turbobiz or Vidit Khandelwal will not
          act as an intermediary between the product and OpenAI should any end
          user have any complaints with the results produced by the product. We
          do not provide any guarantee that the results generated by the product
          will always be unique or up to the end user&apos; liking, and do not
          take any responsibility for any legal ramifications that the end user
          may face should they create a business using the results generated by
          the product.
        </p>
        <p className="uppercase">
          This product is not, and does not claim to be a qualified business
          professional, consultant, accountant, lawyer, or any such person(s) or
          entity which the end user should consult before formally creating,
          starting, and/or running a real business entity. The end user
        </p>
        <p>
          All results and services are provided as-is without any warranty or
          support of any kind. There is no guarantee that user data or search
          history will be available at all times or stored perpetually. The
          product can be taken offline at any time without any explanation or
          cause. The product&apos;s features can be modified, removed, added, or
          made unavailable without prior notice for any amount of time.
        </p>
        <p>
          The only sign in method available in this product is Sign in with
          Google (Google OAuth). Google reserves their right to temporarily or
          permanently ban Google accounts that violate their terms of service.
          The product has no control over Google&apos;s administration of
          accounts, and loss of access of an end user to their Google Account
          will result in a loss of access to this product as well. We do not
          take any responsibility in such cases, and the end user should direct
          their concerns about Google account access exclusively with Google.
          Use of Google OAuth does not give the product or us acccess to any
          personal data of the user, other than account-related information
          required for normal satisfactory functioning of all the currently
          available features of the product.
        </p>
        <p className="uppercase">
          THE PRODUCT DOES NOT HAVE ACCESS TO ANY PERSONAL USER INFORMATION,
          SUCH AS GOOGLE SEARCH HISTORY, EMAILS, CALENDAR, TASKS, PHOTOS, ETC.
        </p>
        <p>
          This is the information about the user available to the product as a
          result of Google OAuth:
        </p>
        <ul className="flex flex-col ml-4">
          <li>
            Display Name <Code>displayName</Code> as on the Google Account.
          </li>
          <li>
            Phone Number <Code>phoneNumber</Code> as on their Google profile.
          </li>
          <li>
            Profile Photo URL <Code>phoneNumber</Code> as on their Google
            profile.
          </li>
          <li>
            App-level Unique Identifier or <Code>uid</Code>: Unique to the
            user&apos;s account on Turbobiz.
          </li>
        </ul>
        <p className="uppercase">
          Irrespective of the data provided to the product as a result of Google
          sign-in, these are the account identifiers used by the product as of
          now. Despite email addresses and phone numbers being available to the
          product as a result of using OAuth, they are neither used for
          identifying users nor for any operational or feature-based purposes.
        </p>
        <ul className="flex flex-col ml-4">
          <li>
            Display Name as on the Google Account or <Code>displayName</Code>:
            Used for personalization of the product&apos;s user interface (UI).
          </li>
          <li>
            Unique Identifier or <Code>uid</Code>: A unique alphanurmeric string
            of characters used for attaching user information such as search
            history to their account in Firestore, without using personally
            identifiable markers.
          </li>
        </ul>
        <p>
          OpenAI, GPT, GPT-3.5, GPT-4, Google, and the Google G Logo are
          registered trademarks of the respective parties, and are used within
          their terms of service. The product is not endorsed, affiliated, or
          financially related to either Google or OpenAI.
        </p>
        <div>
          <PrimaryLink
            variant="outline"
            external={true}
            href="https://github.com/csvidit/turbobiz"
          >
            GitHub Repository and README
          </PrimaryLink>
        </div>
        <div className="inline flex-wrap">
          <p className="inline w-fit">
            For any further queries, please contact me at
          </p>
          <SecondaryLink
            href="mailto:cs@viditkhandelwal.com"
            external={true}
            inline={true}
          >
            cs@viditkhandelwal.com
          </SecondaryLink>
        </div>
      </div>
    </div>
  );
};

export default About;
